# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7711ec24-0dc6-45d4-915d-4c8c46bac21b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F4B1-68DA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/norpie/repos" =
    { device = "//192.168.0.31/repos";
      fsType = "cifs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b6469478-9c7b-41d4-9b8c-ed3bc0df158b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
